---
lego:
  proxy:
    http_proxy: "http://10.1.2.3:8080"
    https_proxy: "http://10.1.2.3:8080"
  ovh:
    endpoint: "ovh-eu"
    application_key: "my_app_key"
    application_secret: "my_app_secret"
    consumer_key: "my_consumer_key"
  renew_threshold_in_days: 20
  certs:
    mycert: |
      {
        "cname": "site.mydomain.com",
        "email": "myemail@mydomain.com",
        "lego_server": "https://acme-staging-v02.api.letsencrypt.org/directory",
        "dns_provider": "ovh"
      }
